version: '2'

networks:
  private:
    driver: bridge

services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks:
      - private
    container_name: hub-container
  chrome:
    image: selenium/node-chrome-debug
    links: [hub]
    networks:
      - private
    external_links:
      - myapplication_frontend_1:pdftables
    ports:
      - 5900:5900
    depends_on:
        - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      #DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
      - ./integration-data:/integration-data

  firefox:
    image: selenium/node-firefox-debug
    links: [hub]
    networks:
      - private
    external_links:
      - myapplication_frontend_1:pdftables
    ports:
      - 5901:5900
    depends_on:
        - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      #DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - ./integration-data:/integration-data

