version: '2'

networks:
  private:
    driver: bridge

services:
  hub:
    container_name: hub-container
    image: selenium/hub
    environment:  
      SE_OPTS: -debug true
    stdin_open: true
    tty: true
    ports:
      - 4444:4444
    networks:
      - private    
  chrome:
    image: selenium/node-chrome-debug
    links: [hub]
    #external_links:
    #  - myapplication_frontend_1:pdftables
    ports:
      - 5900:5900
    depends_on:
        - hub
    environment: 
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      #DBUS_SESSION_BUS_ADDRESS=/dev/null
    stdin_open: true
    tty: true
    volumes:
      #- /dev/shm:/dev/shm
      - ./integration-data:/integration-data
    networks:
      - private

  firefox:
    image: selenium/node-firefox-debug
    links: [hub]
    #external_links:
    #  - myapplication_frontend_1:pdftables
    ports:
      - 5901:5900
    depends_on:
        - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      #DBUS_SESSION_BUS_ADDRESS=/dev/null
    stdin_open: true
    tty: true
    volumes:
      - ./integration-data:/integration-data
    networks:
      - private
