version: '2'

networks:
  private:
    driver: bridge

services:
  hub:
    container_name: hub
    image: selenium/hub
    environment:  
      SE_OPTS: -debug true
    stdin_open: true
    tty: true
    networks:
      - private
  
  chrome:
    container_name: chrome
    image: selenium/node-chrome-debug
    networks:
      - private
    depends_on:
      - hub 
    environment:  
      SE_OPTS: -debug true
      HUB_PORT_4444_TCP_ADDR: hub
    stdin_open: true
    tty: true
    links:
    - hub:hub
    ports:
    - 5901:5900/tcp
    networks:
      - private
  
  firefox:
    container_name: firefox
    image: selenium/node-firefox-debug:3.3.0
    networks:
      - private
    depends_on:
    - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      SE_OPTS: -debug true
    stdin_open: true
    tty: true
    links:
    - hub:hub
    ports:
    - 5900:5900/tcp
    networks:
      - private
    